services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL:-https://api.banglajackpot.online}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-https://banglajackpot.online}
    ports:
      - "127.0.0.1:3020:3000"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    environment:
      NODE_ENV: production
      API_URL: ${API_URL:-https://api.banglajackpot.online}
      NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-https://banglajackpot.online}
      NEXT_PUBLIC_SOCKET_URL: ${NEXT_PUBLIC_SOCKET_URL:-https://api.banglajackpot.online}
    restart: unless-stopped
